- id: shellcheck
  name: shellcheck
  description: Test shell scripts with shellcheck
  entry: sh -c 'shellcheck -f diff | patch -p1'
  language: system
  types: [shell]
  require_serial: true # shellcheck can detect sourcing this way
