{% set name = 'LFPy' %}
{% set version = "1.1.3" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/lfpy/{{name}}-{{ version }}.tar.gz
  sha256: 5c3e5b9c2e408b49bd72bbbaaed5eedf0c060fe54979674ac46472350af16d1c

build:
  number: {{ build }}

requirements:
  build:
    - toolchain
    - python
    - pip
    - cython
    - numpy <1.13
    - neuron
  run:
    - python
    - setuptools
    - cython
    - numpy <1.13
    - scipy
    - matplotlib
    - h5py
    - mpi4py
    - neuron

test:
  imports:
    - LFPy
