{% set name = 'LFPy' %}
{% set version = "2.0rc3" %}
{% set build = 1 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/lfpy/{{name}}-{{ version }}.tar.gz
  sha256: ae146eb7c7723a383bbec438e8f3d9692b8439d873e79391a500a0bdece32bef

build:
  number: {{ build }}
  script: "pip install -v --no-binary :all: --no-deps ."

requirements:
  build:
    - toolchain
    - python
    - pip
    - cython
    - numpy 1.13.* *openblas*
    - neuron 7.4.*
  run:
    - python
    - setuptools
    - python-csa >=0.1.8
    - cython
    - numpy 1.13.* *openblas*
    - scipy
    - matplotlib
    - h5py
    - mpi4py
    - neuron 7.4.*

test:
  imports:
    - LFPy
