{% set name = "opencarp" %}
{% set version = "9.0" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  # simulator/build_info.py means build can only be done from git
  # not the published source distributions
  git_url: https://git.opencarp.org/openCARP/openCARP
  git_ref: v{{ version }}
  # url: https://git.opencarp.org/api/v4/projects/16/packages/generic/openCARP-inclSubmodules/v{{ version }}/openCARP-v{{ version }}-inclSubmodules.zip
  # sha256: 8c43bbc4e18a7de16271626339a6edd60d38fa8d467c0724d71c9f5c45b71527
  patches:
    - cpp-env.patch

build:
  number: {{ build }}
  run_exports:
    # I don't know how compatibility works, so force rebuilds
    - {{ pin_compatible(name, exact=True) }}

requirements:
  build:
    - binutils
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    # # - gengetopt not packaged yet, from apt for now
    - pkg-config
    - python 3.9
  host:
    - petsc 3.16
    - mpich
    - zlib
    - liblapack
    - libblas
  run:
    - python >=3.6
    - liblapack
    - libblas
    - petsc
    - zlib

test:
  commands:
    - bench

about:
  home: https://opencarp.org
  license: Academic Public License
  license_file: LICENSE.md
  summary: Cardiac Electrophysiology Simulator
