{% set version = '3.7.6' %}
{% set sha256 = 'b07f7b4e57d75f982787bd8169f7b8debd5aee2477293da230ab6c80a52c6ef8' %}
{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set mpi = os.environ.get('MPI_VARIANT', 'mpich') %}
{% set mpi_version = {'mpich': '3.2.*', 'openmpi': '3.0.*'}[mpi] %}
{% set build=0 %}

package:
  name: petsc
  version: {{version}}

source:
  fn: petsc-{{version}}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  skip: true  # [win]
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  string: carp_{{build}}

requirements:
  build:
    - toolchain
    - gcc
    - python 2.7.*
    - cmake
    - {{ mpi }} {{ mpi_version }}
  run:
    - libgcc  # [linux]
    - {{ mpi }} {{ mpi_version }}

test:
  source_files:
    - src/snes/examples/tests
  commands:
    - conda inspect linkages petsc  # [not win]

about:
  home: http://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
