{% set name = 'browndye' %}
{% set version = "2018.06.22" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  # url: https://browndye.ucsd.edu/browndye.tar.gz
  url: file:///opt/conda/conda-bld/browndye.tar.gz
  sha256: 98e99faba797c3c5dc6893370e4e5fe92574b3fd5adc0e83cbe0c34e2531df87

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  source_files:
    - thrombin-example
  requires:
    - apbs
