{% set name = 'browndye' %}
{% set version = "2021.2.20" %}
{% set tag = "20-Feb-21" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://bitbucket.org/gahuber95/browndye2/get/{{ tag }}.tar.gz
  sha256: 78d18ea4146de8d940bff754deacc8a41c6ebc49355f58f10d8caa3f01a25011
  patches:
    - makefile-env.patch
    - ldflags.patch

build:
  number: {{ build }}

requirements:
  build:
    - binutils
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - ocaml
  host:
    - expat
    - liblapack
  run:
    - expat
    - liblapack
    - apbs

test:
  source_files:
    - browndye2/examples

about:
  home: https://browndye.ucsd.edu
  license: MIT
  license_file: browndye2/COPYRIGHT
  summary: Brownian Dynamics of Biological Molecules
