apiVersion: v1
description: "jupyterhub deployment for simula summer school"
version: 0.0.0
name: jupyterhub-simula
dependencies:
  # Ingress-Nginx to route network traffic according to Ingress resources using
  # this controller from within k8s.
  # Source code:   https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
  # App changelog: https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md
  - name: ingress-nginx
    version: 3.26.0
    repository: https://kubernetes.github.io/ingress-nginx

  # Prometheus for collection of metrics.
  # Source code:   https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  # App changelog: https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md
  - name: prometheus
    version: 13.6.0
    repository: https://prometheus-community.github.io/helm-charts

  # Grafana for dashboarding of metrics.
  # Source code:   https://github.com/grafana/helm-charts/tree/main/charts/grafana
  # App changelog: https://github.com/grafana/grafana/blob/master/CHANGELOG.md
  - name: grafana
    version: 6.7.2
    repository: https://grafana.github.io/helm-charts

  - name: jupyterhub
    version: 0.11.1-n361.h166e2157
    repository: https://jupyterhub.github.io/helm-chart
