dependencies:
 - name: nginx-ingress
   version: 0.17.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 6.2.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 1.2.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: jupyterhub
   version: v0.7-0e1225e
   repository: https://jupyterhub.github.io/helm-chart
