{% set version = "7.4" %}
{% set build = 1 %}

package:
  name: neuron
  version: {{ version }}

source:
  fn: nrn-{{ version }}.tar.gz
  url: http://www.neuron.yale.edu/ftp/neuron/versions/v{{ version }}/nrn-{{ version }}.tar.gz
  sha256: 1403ba16b2b329d2376f4bf007d96e6bf2992fa850f137f1068ad5b22b432de6

build:
  number: {{ build }}

requirements:
  build:
    - toolchain
    - python
    - bison
    - flex
    - libtool
    - autoconf

test:
  files:
    - Nap_Et2.mod
  imports:
    - neuron
