{% set version = "7.5" %}
{% set build = 0 %}

package:
  name: neuron
  version: {{ version }}

source:
  fn: nrn-{{ version }}.tar.gz
  url: https://www.neuron.yale.edu/ftp/neuron/versions/v{{ version }}/nrn-{{ version }}.tar.gz
  sha256: 67642216a969fdc844da1bd56643edeed5e9f9ab8c2a3049dcbcbcccba29c336

build:
  number: {{ build }}
  run_exports:
    - pin_compatible("neuron", max_pin="x.x", min_pin="x.x")

requirements:
  build:
    - toolchain
    - python
    - bison
    - flex
    - libtool
    - autoconf
    - readline 7.*
    - ncurses
  run:
    - python
    - readline 7.*
    - ncurses
    - scipy

test:
  files:
    - Nap_Et2.mod
  imports:
    - neuron
    - neuron.rxd
