channels:
  - conda-forge
  - defaults
  - minrk
dependencies:
  # basics, since this is starting from micromamba
  - mamba
  - conda

  # scientific packages
  - fenics=2019.1.0
  - mshr=2019.1.0
  - sympy
  - neuron
  - lfpy
  - python-neo

  # packaged in this repo:
  - browndye=2022.3
  - opencarp=9
  # TODO:
  # - carputils?

  # basic Python
  - python=3.9
  - black
  - isort
  - matplotlib-base
  - cython
  - scipy
  - seaborn
  - numba
  - numpy
  - pandas
  - altair
  - scikit-learn
  - pytorch
  - pytest
  - wurlitzer

  # IPython/Jupyter
  # - nodejs=14
  - jupyterlab
  - jupyterhub-base=2.2.2
  - jupyterlab_code_formatter
  - jupyterlab-git
  - nbdime
  - notebook
  - ipykernel
  - ipywidgets
  - nbgitpuller
