channels:
  - conda-forge
  - defaults
  - minrk
dependencies:
  # basics, since htis is starting from micromamba
  - mamba
  - conda
  # scientific packages
  - fenics=2019.1.0
  - mshr=2019.1.0
  - sympy
  - neuron
  - lfpy
  - python-neo
  
  # packaged in this repo:
  - browndye
  - opencarp
  # TODO:
  # - carputils?
  
  # basic Python
  - python=3.8
  - matplotlib
  - cython
  - scipy
  - numba
  - numpy
  - pandas
  - altair
  - scikit-learn

  # IPython/Jupyter
  - nodejs=14
  - jupyterlab
  - jupyterhub-base=1.3.0
  - nbdime
  - notebook
  - ipykernel
  - ipywidgets
  - octave_kernel
