channels:
  - conda-forge
  - defaults
  - minrk
  - electrostatics
dependencies:
  # scientific packages
  # - fenics=2018.1.0
  - sympy=1.1
  # basic Python
  - python=3.6
  - matplotlib
  - scipy
  - numpy
  - pandas
  - altair
  # IPython/Jupyter
  - jupyterlab
  - nbdime=1.0
  - notebook=5.6
  - ipykernel
  - ipywidgets=7.2
