channels:
  - conda-forge
  - defaults
  - minrk
dependencies:
  # scientific packages
  - fenics=2017.2.0
  - neuron=7.4
  - lfpy=2.0
  # basic Python
  - python=3.6
  - matplotlib
  - scipy
  - numpy
  - pandas
  # IPython/Jupyter
  - nbdime
  - notebook=5.4
  - ipykernel
  - ipywidgets=7.2
  # octave
  - octave
  - octave_kernel
  - ghostscript
