channels:
  - conda-forge
  - defaults
  - minrk
  - electrostatics
dependencies:
  # scientific packages
  - fenics=2019.1.0
  - sympy=1.1
  - neuron=7.6.7
  # basic Python
  - python=3.6
  - matplotlib
  - cython
  - scipy
  - numba
  - numpy
  - pandas
  - altair
  # IPython/Jupyter
  - nodejs=10.*
  - jupyterlab
  - nbdime=1.0
  - notebook=5.7
  - ipykernel
  - ipywidgets=7.4
  - octave_kernel
