channels:
  - conda-forge
  - defaults
  - minrk
dependencies:
  - python=3.6
  - fenics=2017.2.0
  - neuron=7.4
  - lfpy=2.0
  - nbdime
  - matplotlib
  - scipy
  - numpy
  - pandas
  - notebook
  - ipykernel
